---
title: "Git Instructions"
author: "Michael Sciole"
date: "2023-03-28"
output:
  bookdown::html_document2:
    theme: lumen
    toc: yes
    toc_float: yes
    df_print: kable
    css: MyLab.css 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Using Git

### What is Git Branching and do I need it?

  Group projects can be a pain, especially in software development. From sloppy code getting put into production to loosing track of the last working version of your software, code monkeys like us need to be very careful. Git branching is the best way to keep your testing and production code separated and organized. It is the most pervasive version control system in software development for two reasons, it is lightweight and cheap. Other version controls can be expensive and clog up your disk space. Git won't slow down your computer and it won't cost you or your team a dime. When making and debugging a new feature git branching is critical in keeping your production from breaking. By creating new branches Git allows you to keep unfinished code out of your product, making it easier to go back and find working versions of your code after finding a bug, and making it safer to add new features to your software or application.

### Do I need to be a veteran coder?

  Git is prided on how intuitive and user friendly it is. Most commands are about two or three words and only interact with your GitHub repository. By using branches it can even become more difficult to push bad code to your production branch than not. So no, you can be as novice to the world of software as you like!



## Let's Git Started!

  Using git is as simple as typing “git init” into the directory you want to work in. This command initializes git commands in a repository giving you access to do all sorts of cool capabilities! 

### Instructions for Mac and Linux:

Before we get started make sure your accessing your local drive through a terminal on your computer. If your using a Mac or a Linux machine this will be simple, just open the *terminal* application. Got it pulled up? Well, we're getting started anyways:

1. The first step in any project is to use the terminal to navigate to wherever you would like to store your project. ```cd user/project```
    + user should be your user name and project should be where you're storing you git project.
    + To keep things simple make a dedicated directory on your local drive to store all of your git projects, or be prepared to do alot of searching!

2. Once in the desired directory run the following command: ```git init```. 
    + This will download the git dependencies into that directory

3. Create some files! 
    + You should always create a ReadME.md file in the base of your Git repository, but no project is underway until there is documentation and source code, so you should create directories for these within your repository.

4. Branch out! Run ```git branch main``` to create the main branch you will store your production code in.

5. Make another branch ```git branch branch-name``` and name it whatever you like! 
    + You **never** want to push code directly to your main branch, unless it is *only* the ReadMe.md file. That branch is for your working production code, and you don't want to risk putting broken code onto it.
    
6. Get onto your new branch and off of your main by running ```git checkout branch-name```. Now we can start staging our code.

7. Set the Stage! Now we must track our changes and "stage" our code. To do this run ```git add path/to/file``` to stage specific files, or ```git add --all``` to stage all modified files.

8. Make a Commitment! Now we’re ready to commit our files to be pushed to GitHub. Run the command ```git commit -m “Description of commit”```. This will commit your work to be pushed to a repository your team can access.

9. Get it on GitHub! Now is when we create the remote repository we will push our code. Go to GitHub.com and click “New Repository” in the top right corner of the page (see fig 1.1). Name your repository and set it to public, then click create repository. Copy the url on the next page (see fig 1.2). Now run the command “git remote add origin <URL>” on your terminal. Boom! Now your connected to GitHub! Time to push your work!

10. Push it, Push it! Simply run the command ```git push -u origin branch-name``` and enter your GitHub credentials when prompted (note that a git token may be required if your password does no work)
    + To create a git token go to settings -> Developer settings -> personal access tokens -> tokens
    + Click generate new token, and set the privileges so that you will have “repo access”
    + Use this token as your password when pushing to your repository
    
That’s that! Your local repository will have all the files you added and committed, and your team will have access to the repo as well, assuming you let them touch your work that is!


### Instructions for Windows:
